Repository nithishniz11/songs, pull requests merged in 2022-06, with the labels that each got.

#1 Branch 2
  README.md
  song1
Labels: duplicate

#4 Branch 2
  song1
Labels: documentation

#5 Update song1
  song1
Labels: documentation, wontfix
